import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from theme import (
    NEON_GREEN, NEON_GREEN_GLOW, NEON_GREEN_DIM,
    PRIMARY, PRIMARY_HOVER,
    BG_DARK, BG_CARD, BG_INPUT, BORDER,
    TEXT_PRIMARY, TEXT_SECONDARY,
    ACCENT_DARK, ACCENT_DARK_DIM,
    BG_LIGHT, BG_CARD_LIGHT, BG_INPUT_LIGHT, BORDER_LIGHT,
    TEXT_PRIMARY_LIGHT, TEXT_SECONDARY_LIGHT,
    ACCENT_LIGHT, SECONDARY_LIGHT_DARK,
    LOW_STOCK_YELLOW, LOW_STOCK_RED, RADIUS, RADIUS_SM,
    DARK_THEME, LIGHT_THEME,
    CARD_STYLE, CARD_STYLE_GLOW, CARD_STYLE_LOW, CARD_STYLE_CRITICAL,
)
